#!/usr/bin/env python3
"""
Assembles LGAM subpages from shared partials + per-page content.
Run from anywhere: python gds-local/_build/build.py

Zero external dependencies — uses only Python stdlib.

Page statuses (for built pages in _pages/):
  - published: built to root (live) AND preview/. Linked from index.
  - draft:     built to preview/ only. Not linked from index.
  - modified:  built to preview/ only (root keeps last-published version). Linked from index.

Hand-authored pages (index.html, gds-local-alt.html):
  - Root file = published version (edit directly to publish)
  - If a working copy exists in _build/_hand/, it is used for preview/ instead
  - This allows unapproved changes to be previewed without affecting the live site
"""

import os
import re
import shutil
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
GDS_LOCAL_DIR = os.path.dirname(SCRIPT_DIR)
PARTIALS_DIR = os.path.join(SCRIPT_DIR, "_partials")
PAGES_DIR = os.path.join(SCRIPT_DIR, "_pages")
HAND_DIR = os.path.join(SCRIPT_DIR, "_hand")
PREVIEW_DIR = os.path.join(GDS_LOCAL_DIR, "preview")

# Hand-authored files to include in preview
HAND_AUTHORED_FILES = ["index.html", "gds-local-alt.html"]

GENERATED_COMMENT = "<!-- Generated by build.py — do not edit directly -->\n"


def read_partial(name):
    with open(os.path.join(PARTIALS_DIR, name), "r", encoding="utf-8") as f:
        return f.read()


def parse_page(filepath):
    """Parse a page source file into front matter dict and content blocks."""
    with open(filepath, "r", encoding="utf-8") as f:
        raw = f.read()

    # Parse front matter
    if not raw.startswith("---"):
        raise ValueError(f"{filepath}: missing front matter (must start with ---)")

    end = raw.index("---", 3)
    fm_block = raw[3:end].strip()
    body = raw[end + 3:].strip()

    front_matter = {}
    for line in fm_block.splitlines():
        if ":" in line:
            key, val = line.split(":", 1)
            front_matter[key.strip()] = val.strip()

    # Extract tagged blocks
    def extract_block(tag):
        pattern = f"<{tag}>(.*?)</{tag}>"
        m = re.search(pattern, body, re.DOTALL)
        return m.group(1) if m else ""

    blocks = {
        "style": extract_block("style"),
        "nav_contents": extract_block("nav-contents"),
        "main_content": extract_block("main-content"),
        "page_script": extract_block("page-script"),
    }

    return front_matter, blocks


def build_page(filename, front_matter, blocks):
    """Assemble a full HTML page from partials and page-specific blocks."""
    head_open = read_partial("head-open.html")
    layout_css = read_partial("layout-css.html")
    header = read_partial("header.html")
    sidebar_lgam = read_partial("sidebar-lgam.html")
    footer = read_partial("footer.html")

    # Replace template variables in head
    title = front_matter.get("title", "Page")
    head_open = head_open.replace("{{ title }}", title)

    # Assemble
    parts = []
    parts.append(GENERATED_COMMENT)
    parts.append(head_open)

    # Page-specific CSS
    if blocks["style"].strip():
        parts.append(blocks["style"])
        parts.append("\n")

    # Layout CSS
    parts.append(layout_css)
    parts.append("  </style>\n</head>\n\n")

    # Body: header + phase banner
    parts.append(header)
    parts.append("\n")

    # Content wrapper with sidebar + main
    parts.append("  <div class=\"app-content-wrapper\">\n")
    parts.append("    <nav class=\"app-sidebar\" aria-label=\"Page navigation\">\n")
    parts.append("      <h2 class=\"app-navigation__heading\">Contents</h2>\n")
    parts.append("      <ul class=\"app-navigation\">\n")
    parts.append(blocks["nav_contents"])
    parts.append("\n      </ul>\n")
    parts.append(sidebar_lgam)
    parts.append("    </nav>\n\n")
    parts.append("      <main class=\"app-main-content\" id=\"main-content\" role=\"main\">\n")
    parts.append(blocks["main_content"])
    parts.append("\n      </main>\n")
    parts.append("  </div>\n\n")

    # Footer
    parts.append(footer)

    # Page-specific script
    if blocks["page_script"].strip():
        parts.append("\n  <script>\n")
        parts.append(blocks["page_script"])
        parts.append("\n  </script>\n")

    parts.append("</body>\n</html>\n")

    return "".join(parts)


def update_index_links(pages):
    """Insert/remove 'View X detail' links in index.html based on page status."""
    index_path = os.path.join(GDS_LOCAL_DIR, "index.html")
    if not os.path.exists(index_path):
        print("  [skip] index.html not found")
        return

    with open(index_path, "r", encoding="utf-8") as f:
        html = f.read()

    original = html

    for filename, fm in pages:
        title = fm.get("title", "")
        status = fm.get("status", "draft")
        if not title:
            continue

        # Build the link paragraph we want to insert/find
        link_para = (
            f'<p class="govuk-body govuk-!-margin-top-3 govuk-!-margin-bottom-0">'
            f'<a href="{filename}" class="govuk-link">View {title} detail &rarr;</a></p>'
        )

        # Pattern to find existing auto-generated link for this file
        link_pattern = re.compile(
            r'<p class="govuk-body govuk-!-margin-top-3 govuk-!-margin-bottom-0">'
            r'<a href="' + re.escape(filename) + r'"[^>]*>View [^<]+ detail[^<]*</a></p>\n?'
        )

        # Find the item whose summary text matches the page title (case-insensitive)
        # Pattern: <summary...><span...>Title text</span></summary>
        summary_pattern = re.compile(
            r'(<details[^>]*>.*?<summary[^>]*>\s*<span[^>]*>)\s*'
            + re.escape(title)
            + r'\s*(</span>\s*</summary>.*?<div class="govuk-details__text">)(.*?)(</div>\s*</details>)',
            re.DOTALL | re.IGNORECASE,
        )

        match = summary_pattern.search(html)
        if not match:
            continue

        details_text = match.group(3)

        # Published and modified pages get links; draft pages don't
        if status in ("published", "modified"):
            # If link already present, leave it
            if link_pattern.search(details_text):
                continue
            # Insert link after the first <p> in the details text
            first_p_end = re.search(r'</p>', details_text)
            if first_p_end:
                insert_pos = match.start(3) + first_p_end.end()
                html = html[:insert_pos] + "\n                    " + link_para + html[insert_pos:]
        else:
            # Draft: remove link if present
            html = link_pattern.sub("", html)

    if html != original:
        with open(index_path, "w", encoding="utf-8") as f:
            f.write(html)
        print("  [updated] index.html")
    else:
        print("  [unchanged] index.html")


def generate_preview_index(pages_meta):
    """Generate a simple link index page listing all preview pages."""
    lines = []
    lines.append("<!DOCTYPE html>")
    lines.append('<html lang="en"><head>')
    lines.append('<meta charset="utf-8">')
    lines.append('<title>LGAM Preview Index</title>')
    lines.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    lines.append('<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/govuk-frontend@5.13.0/dist/govuk/govuk-frontend.min.css">')
    lines.append("</head><body class=\"govuk-template__body\">")
    lines.append('<div class="govuk-width-container" style="padding: 30px 0;">')
    lines.append('<h1 class="govuk-heading-l">LGAM Preview Pages</h1>')
    lines.append('<p class="govuk-body">These pages are drafts or have unapproved modifications. They are not linked from the live site.</p>')

    # Hand-authored pages
    lines.append('<h2 class="govuk-heading-m">Hand-authored pages</h2>')
    lines.append('<ul class="govuk-list govuk-list--bullet">')
    for filename in HAND_AUTHORED_FILES:
        preview_path = os.path.join(PREVIEW_DIR, filename)
        if os.path.exists(preview_path):
            hand_path = os.path.join(HAND_DIR, filename)
            state = "modified" if os.path.exists(hand_path) else "published"
            lines.append(f'<li><a class="govuk-link" href="{filename}">{filename}</a> <strong class="govuk-tag govuk-tag--{("yellow" if state == "modified" else "green")}">{state}</strong></li>')
    lines.append("</ul>")

    # Built pages
    lines.append('<h2 class="govuk-heading-m">Built pages</h2>')
    lines.append('<table class="govuk-table">')
    lines.append('<thead class="govuk-table__header"><tr>')
    lines.append('<th class="govuk-table__header">Page</th>')
    lines.append('<th class="govuk-table__header">Title</th>')
    lines.append('<th class="govuk-table__header">Status</th>')
    lines.append("</tr></thead>")
    lines.append('<tbody class="govuk-table__body">')

    tag_colours = {"published": "green", "draft": "grey", "modified": "yellow"}
    for filename, fm in pages_meta:
        title = fm.get("title", filename)
        status = fm.get("status", "draft")
        colour = tag_colours.get(status, "grey")
        lines.append("<tr class=\"govuk-table__row\">")
        lines.append(f'<td class="govuk-table__cell"><a class="govuk-link" href="{filename}">{filename}</a></td>')
        lines.append(f'<td class="govuk-table__cell">{title}</td>')
        lines.append(f'<td class="govuk-table__cell"><strong class="govuk-tag govuk-tag--{colour}">{status}</strong></td>')
        lines.append("</tr>")

    lines.append("</tbody></table>")
    lines.append("</div></body></html>")

    index_path = os.path.join(PREVIEW_DIR, "directory.html")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\n  Preview index: preview/directory.html")


def main():
    if not os.path.isdir(PAGES_DIR):
        print(f"Error: pages directory not found: {PAGES_DIR}", file=sys.stderr)
        sys.exit(1)

    page_files = sorted(
        f for f in os.listdir(PAGES_DIR) if f.endswith(".html")
    )

    if not page_files:
        print("No page sources found in _pages/")
        return

    # Ensure preview directory exists
    os.makedirs(PREVIEW_DIR, exist_ok=True)

    print(f"Building {len(page_files)} page(s)...\n")

    pages_meta = []

    for filename in page_files:
        filepath = os.path.join(PAGES_DIR, filename)
        fm, blocks = parse_page(filepath)
        output = build_page(filename, fm, blocks)
        status = fm.get("status", "draft")

        # Always write to preview/
        preview_path = os.path.join(PREVIEW_DIR, filename)
        with open(preview_path, "w", encoding="utf-8") as f:
            f.write(output)

        # Only write to root for published pages
        root_path = os.path.join(GDS_LOCAL_DIR, filename)
        if status == "published":
            with open(root_path, "w", encoding="utf-8") as f:
                f.write(output)
            print(f"  [published]  {filename}")
        elif status == "modified":
            # Don't touch root — it retains the last-published version
            print(f"  [modified]   {filename} (preview only, root unchanged)")
        else:
            # Draft — don't write to root (or remove if it exists from a previous state)
            print(f"  [draft]      {filename} (preview only)")

        pages_meta.append((filename, fm))

    # Update index.html links (published + modified get links, draft doesn't)
    print("\nUpdating index.html links...")
    update_index_links(pages_meta)

    # Handle hand-authored files for preview
    print("\nHand-authored pages:")
    for filename in HAND_AUTHORED_FILES:
        hand_path = os.path.join(HAND_DIR, filename)
        root_path = os.path.join(GDS_LOCAL_DIR, filename)
        preview_path = os.path.join(PREVIEW_DIR, filename)

        if os.path.exists(hand_path):
            # Working copy exists — use it for preview (root stays as published)
            shutil.copy2(hand_path, preview_path)
            print(f"  [modified]   {filename} (preview from _hand/, root unchanged)")
        elif os.path.exists(root_path):
            # No working copy — root IS the current version, copy to preview
            shutil.copy2(root_path, preview_path)
            print(f"  [published]  {filename} (copied to preview)")
        else:
            print(f"  [skip]       {filename} (not found)")

    # Generate preview link index
    generate_preview_index(pages_meta)

    print(f"\nPreview: {PREVIEW_DIR}/")
    print("Done.")


if __name__ == "__main__":
    main()
